{{- if empty .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-health-bot.fullname" . }}-secrets
  labels:
    {{- include "ai-health-bot.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 encoded values
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.telegram_bot_token | b64enc | quote }}
  TELEGRAM_CHANNEL_ID: {{ .Values.secrets.telegram_channel_id | quote | b64enc | quote }}
  LLM_API_KEY: {{ .Values.secrets.llm_api_key | b64enc | quote }}
{{- end -}}
